### ISSUE TITLE
Book title and author in admin: manage borrowing 

### ISSUE THREAD

**Issue by meshiyet** [withtahmid/CSE311_PROJECT_GROUP13#8]
![Annotation 2022-08-15 131633](https://user-images.githubusercontent.com/107493183/184592484-ca354b75-2433-4ad0-a79e-0a4f01a178cb.png)
In add borrow, return borrow, and edit borrow:
display the book title and author when ISBN number is entered. It is hard to identify book with just ISBN and admin might make mistake

**Comment by withtahmid** [comment]
Admin can type anything related to the book and the books will show up in the options. Only ISBN is passed to avoid string splitting. I will look into it to make it more efficient. Thanks!
